export const data = [
  {
    avatar: '',
    fullName: 'Nguyen Van A',
    age: 20,
    address: 'So 12, Ng 55, Hai Ba Trung, Ha Noi',
    phone: '012334534656',
    email: 'nguyenvana@gmail.com',
    gender: 'male',
    stars: 3,
  },
  {
    avatar: '',
    fullName: 'Nguyen Van B',
    age: 21,
    address: 'So 12, Ng 55, Hoang Cau, Ha Noi',
    phone: '012334534656',
    email: 'nguyenvanb@gmail.com',
    gender: 'male',
    stars: 2,
  },
  {
    avatar: '',
    fullName: 'Nguyen Van C',
    age: 23,
    address: 'So 12, Ng 55, Xa Dan, Ha Noi',
    phone: '012334534656',
    email: 'nguyenvanc@gmail.com',
    gender: 'male',
    stars: 3.5,
  },
  {
    avatar: '',
    fullName: 'Nguyen Thi D',
    age: 18,
    address: 'So 12, Ng 55, Xa Dan, Ha Noi',
    phone: '012334534656',
    email: 'nguyenthid@gmail.com',
    gender: 'female',
    stars: 4.5,
  },
  {
    avatar: '',
    fullName: 'Nguyen Thi D',
    age: 18,
    address: 'So 12, Ng 55, Xa Dan, Ha Noi',
    phone: '012334534656',
    email: 'nguyenthid@gmail.com',
    gender: 'female',
    stars: 4.5,
  },
]
